### PR TITLE
Update casual use rate to Day Pass rate

### PR DESCRIPTION
**Pull request by FletcherAU**
As suggested by @spondy

### CODE REVIEW

**Comment by FletcherAU** [comment]
@LiaungYip are you happy with the wording here?

**Comment by LiaungYip** [comment]
I suspect there's a few more s/Casual/Day pass/ substitutions to make in various places on the wiki.

The Tools directory, in particular, is a hotbed for fees information  embedded on individual pages.

There's a balance to strike between usefulness to members (where duplicate info on multiple pages helps) and ease of maintenance (where duplicate info hurts.)

As one of the people maintaining the wiki, I  vote to make my life easier by eradicating all fees information all pages except the actual fees page, inserting references to that page where appropriate.

Notwithstanding the above, this PR looks fine to me. :)

**Comment by FletcherAU** [comment]
Put to committee

**Comment by FletcherAU** [comment]
Motion passed

**Pull request merged**
